[package]
name = "futures-async-stream"
version = "0.1.5"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/futures-async-stream"
homepage = "https://github.com/taiki-e/futures-async-stream"
documentation = "https://docs.rs/futures-async-stream"
keywords = ["async", "future", "futures", "stream", "macros"]
categories = ["asynchronous", "no-std"]
readme = "README.md"
description = """
Async stream for Rust and the futures crate.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
members = ["futures-async-stream-macro", "tests/doc"]

[dependencies]
futures-async-stream-macro = { version = "=0.1.5", path = "futures-async-stream-macro", default-features = false }
futures-core = { version = "0.3", default-features = false }
futures-sink = { version = "0.3", default-features = false }
pin-project = "0.4.10"
futures = { version = "0.3", default-features = false, features = ["executor"] }

[dev-dependencies]
trybuild = "1.0"
futures = { version = "0.3", default-features = false }
