name: CI

permissions: {}

on:
  pull_request:
  push:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  # NB: sync with miri job's --exclude option
  EXCLUDE: --exclude futures-async-stream-internal-codegen

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  tidy:
    uses: taiki-e/github-actions/.github/workflows/tidy.yml@1bb80ca038216cd1fb7b6ca6d76240b3772963ab # main
    permissions:
      security-events: write # for github/codeql-action/*
  miri:
    needs: tidy
    uses: taiki-e/github-actions/.github/workflows/rust-miri.yml@1bb80ca038216cd1fb7b6ca6d76240b3772963ab # main
    with:
      # NB: sync with env.EXCLUDE
      args: --exclude futures-async-stream-internal-codegen

  test:
    needs: tidy
    strategy:
      fail-fast: false
      matrix:
        rust:
          # This is the minimum supported Rust version of this crate.
          # When updating this, the reminder to update the minimum supported
          # Rust version in README.md and .clippy.toml.
          - nightly-2024-04-25
          - nightly
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: taiki-e/checkout-action@7d1e50e93dc4fb3bba58f85018fadf77898aee8b # v1.4.2
      - uses: taiki-e/install-action@c070f87102a1c75b3183910f391c1cb887fe13c8 # v2.77.6
        with:
          tool: |
            rust@${{ matrix.rust }} + rust-src + thumbv6m-none-eabi
            cargo-hack
            cargo-minimal-versions
            ${{ matrix.rust == 'nightly' && 'cargo-careful' || '' }}
          fallback: none
      - run: cargo test --workspace --all-features ${EXCLUDE} --no-run
      - run: cargo test --workspace --all-features ${EXCLUDE}
        if: matrix.rust == 'nightly'
      - run: cargo careful test --workspace --all-features ${EXCLUDE}
        env:
          RUSTDOCFLAGS: ${{ env.RUSTDOCFLAGS }} -Z randomize-layout
          RUSTFLAGS: ${{ env.RUSTFLAGS }} -Z randomize-layout
        if: matrix.rust == 'nightly'
      - run: cargo hack build --workspace --no-private --feature-powerset --no-dev-deps
      - run: cargo build --manifest-path tests/no-std/Cargo.toml --target thumbv6m-none-eabi
      - run: cargo minimal-versions build --workspace --no-private --detach-path-deps=skip-exact --all-features
      - run: cargo minimal-versions build --workspace --no-private --detach-path-deps=skip-exact --all-features --direct
