name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+.*

defaults:
  run:
    shell: bash

jobs:
  create-release:
    if: github.repository_owner == 'taiki-e'
    uses: taiki-e/github-actions/.github/workflows/create-release.yml@main
    with:
      rust: nightly
      crates: futures-async-stream-macro,.
    permissions:
      contents: write
    secrets: inherit
